version: '2'
services:
  ark:
    image: boerngenschmidt/ark-docker
    environment:
      SERVERMAP: "TheIsland"
      #SERVERMAP: "Aberration_P"
      SESSIONNAME: "Cavern's End"
      ADMINPASSWORD: "password"
      AUTOUPDATE: 120
      AUTOBACKUP: 60
      WARNMINUTE: 30
      BACKUPONSTART: 1
      UPDATEONSTART: 1
      GID: 1000
      UID: 1000
    ports:
      - 7777:7777
      - 7777:7777/udp
      - 7778:7778
      - 7778:7778/udp
      - 27015:27015
      - 27015:27015/udp
      - 32330:32330
    volumes:
      - /home/ubuntu/ark:/ark
      - /home/ubuntu/logs:/home/steam/Steam/logs

