version: '2'
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - /home/ubuntu/mc:/data
    environment:
      VERSION: SNAPSHOT
      EULA: "TRUE"
      OPS: LG_Ender
      MOTD: "Cavern's End"
      MODE: survival
      VIEW_DISTANCE: 15
      LEVEL: "2020-03-26"
      ICON: server-icon.png
      INIT_MEMORY: 1G
      MAX_MEMORY: 2G
    tty: true
    stdin_open: true
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4426"
      - "4327:4327"
    volumes:
      - /home/ubuntu/mc:/opt/rcon-web-admin/db
